version: '3'

services:
  db:
    image: postgres:latest
    container_name: ubike
    restart: always
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: ubike
      POSTGRES_DB: ubike_db
    volumes:
      - ubike_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  ubike_db_data:
    driver: local